"use client";

import { motion } from "framer-motion";
import { FileText, Download, Calendar, Filter } from "lucide-react";
import { Button } from "@/components/ui/button";

import { useState, useEffect } from "react";
import { generateVaultVisionPDF } from "@/lib/pdf-service";
import { API_BASE_URL } from "@/lib/api";

interface DetectionReport {
  id: number;
  asset_name: string;
  similarity: string;
  similarity_score: number;
  risk_level: string;
  status: string;
  timestamp: string;
  ai_analysis: string;
}

export default function ReportsPage() {
  const [reports, setReports] = useState<DetectionReport[]>([]);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    const fetchHistory = async () => {
      try {
        const response = await fetch(`${API_BASE_URL}/api/history`);
        if (response.ok) {
          const data = await response.json();
          setReports(data);
        }
      } catch (error) {
        console.error("Failed to fetch reports:", error);
      } finally {
        setIsLoading(false);
      }
    };

    fetchHistory();
  }, []);

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between mb-8">
        <div>
          <h1 className="text-3xl font-bold text-white tracking-tight">Forensic Reports</h1>
          <p className="text-slate-400 mt-1">Verifiable evidence reports generated by the Gemini 1.5 Evidence Engine.</p>
        </div>
        <div className="flex gap-3">
          <Button variant="outline" className="rounded-full bg-white/5 border-white/10 text-white">
            <Filter className="w-4 h-4 mr-2" />
            Filter
          </Button>
        </div>
      </div>

      {isLoading ? (
        <div className="flex justify-center items-center py-20">
          <div className="h-8 w-8 border-4 border-primary border-t-transparent rounded-full animate-spin" />
        </div>
      ) : reports.length === 0 ? (
        <div className="glass-card p-12 text-center text-slate-500">
          No reports available. Generate reports by analyzing suspect media in the Detector.
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {reports.map((report, i) => (
            <motion.div
              key={report.id}
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              transition={{ delay: i * 0.1 }}
              className="glass-card p-6 flex items-start justify-between group"
            >
              <div className="flex items-start gap-4">
                <div className="p-3 bg-primary/10 rounded-xl">
                  <FileText className="w-6 h-6 text-primary" />
                </div>
                <div>
                  <h3 className="font-bold text-white group-hover:text-primary transition-colors">
                    Forensic Analysis: {report.asset_name}
                  </h3>
                  <div className="flex flex-wrap items-center gap-4 mt-2 text-sm text-slate-500">
                    <span className="flex items-center gap-1.5"><Calendar className="w-4 h-4" /> {new Date(report.timestamp).toLocaleDateString()}</span>
                    <span className={`px-2 py-0.5 rounded-full text-[10px] font-black border ${
                      report.risk_level === 'HIGH' ? 'bg-rose-500/10 text-rose-500 border-rose-500/20' : 'bg-emerald-500/10 text-emerald-500 border-emerald-500/20'
                    }`}>
                      {report.risk_level} RISK
                    </span>
                    <span className="font-mono text-xs">{report.similarity} Match</span>
                  </div>
                </div>
              </div>
              <Button 
                variant="ghost" 
                size="icon" 
                onClick={() => generateVaultVisionPDF(
                  report.asset_name,
                  report.ai_analysis,
                  report.similarity_score,
                  report.risk_level
                )}
                className="text-slate-400 hover:text-primary hover:bg-white/5 rounded-full h-10 w-10 flex-shrink-0"
              >
                <Download className="w-5 h-5" />
              </Button>
            </motion.div>
          ))}
        </div>
      )}
    </div>
  );
}

